version: 0.2

phases:
  install:
    commands:
      - echo Instalar dependências
      - apt-get update
      - apt-get install -y java-21-amazon-corretto-jdk
      - ./gradlew clean
  build:
    commands:
      - echo Compilando o projeto
      - ./gradlew build
artifacts:
  files:
    - build/libs/**/*.jar
