version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - echo "Instalando dependências..."
      - ./gradlew clean build
  build:
    commands:
      - echo "Executando testes..."
      - ./gradlew test jacocoTestReport
  post_build:
    commands:
      - echo "Analisando cobertura de código..."
      - ./gradlew jacocoTestReport
artifacts:
  files:
    - build/reports/**
  discard-paths: yes
reports:
  jacoco:
    files:
      - 'build/reports/jacoco/test/html/index.html'