version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto21
    commands:
      - echo Instalar dependências
      - chmod +x ./gradlew  # Adiciona permissão de execução ao gradlew
  build:
    commands:
      - echo Compilando o projeto
      - ./gradlew clean build
  post_build:
    commands:
      - echo "Executando testes"
      - ./gradlew test jacocoTestReport jacocoTestCoverageVerification
artifacts:
  files:
    - build/libs/**/*.jar
reports:
  junit:
    files:
      - '**/build/test-results/test/*.xml'
    base-directory: .
  cobertura:
    files:
      - '**/build/reports/jacoco/test/*.xml'
    base-directory: .